FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

#o nginx necessita que pelo menos exista um arquivo php nem que seja em branco
RUN mkdir /var/www/html/ -p && touch /var/www/html/index.php

ENTRYPOINT [ "/docker-entrypoint.sh" ];
CMD ["nginx", "-g", "deamon off;"];